### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by jaimevillegas** [shayan1234554321/warrior-cars#4]
We suggest to you modify the following:

-  Adding `a` tags to `li` elements from the navigation menu.
- Replacing `div class='tab'` to `article class='tab'`.
- Kindly change `display:none` to `visibility` on lines --> https://github.com/shayan1234554321/warrior-cars/blob/Styling-home-for-desktop-mobile-version/index.js#L24-L36
- Instead `add('rotateArrow')` and `remove('rotateArrow')` you can use `toggle('rotateArrow')` on lines --> https://github.com/shayan1234554321/warrior-cars/blob/Styling-home-for-desktop-mobile-version/index.js#L44-L54
- If you plan to extend the code of your functions, it would be a good idea to separate them into different files, or adding comments to each section.

**Comment by shayan1234554321** [comment]
Great issue !! Will work on changes
